### ISSUE TITLE
JZWeekViewFlowLayout crash

### ISSUE THREAD

**Issue by walkerdev777** [zjfjack/JZCalendarWeekView#16]
Hi,

Each time I push another view controller after one minute this is crashing

    @objc private func minuteTick() {
        cachedCurrentTimeComponents.removeAll()
        invalidateLayout()
    }
the file is JZWeekViewFlowLayout.swift, does need something else? thanks

**Comment by zjfjack** [comment]
Hi, I tried to make a quick demo for pushing a new ViewController, everything looks good, no crash.

This function is triggered by Timer to update the current timeline when the time changed.
Also, this timer will be invalid once the class will be destroyed. But when you only push the ViewController, I don't think the `deinit` func will be called.

Could you send me some more error details?

**Comment by walkerdev777** [comment]
Hi, I have downloaded the JZCalendarWeekExample, and just added a simple button in the storyboard, the results is the same,  the app crash after one minute, I just connect button action for push the new viewcontroller, after tap the button and just leave  one minute the app in the new viewcontroller just crash take a look:

![captura de pantalla 2018-09-13 a la s 9 16 59 a m](https://user-images.githubusercontent.com/41090257/45494079-e8b31400-b735-11e8-9f91-4737f93d63ef.png)

**Comment by zjfjack** [comment]
Hi, I tried again with your way but nothing wrong.
Could you send me the example project you edited to my email? zekejeff@gmail.com
Could you also send me your simulator model and os version?
Thanks

**Comment by walkerdev777** [comment]
Hi, sure 
Simulator: iPhone 5s or iPhone 6s iOs 9,3 and 11,4.

I Going to send the email with the project, my email is walkerdev777@gmail.com

Thanks

**Comment by zjfjack** [comment]
I've done some tests, this issue is really strange.
Firstly, it only appears on iOS 9 devices (I don't have any iOS 9 real devices)
Secondly, it only appears after you replace the previous LongPressViewController to the default one.

After doing some debugs, I realise the issue happens when you replace the ViewController.

In iOS 9, the timer for current timeline in previous flowLayout still exists, but once it has been triggered, because this reason (code=[EXC_I386_GPFLT](https://stackoverflow.com/questions/19651788/whats-the-meaning-of-exception-code-exc-i386-gpflt)), then EXC_BAD_ACCESS.
In iOS 10+, nothing will happen, I think Apple change something in the code. However, an issue is that the timer still exists and this timer will be called twice.

So, the main problem is that the flowLayout hasn't been released, then the deinit function is not called at all.

--------two hours later-----------
After spending two hours, I finally find out the problem, because the Timer is strong reference!!
I fixed this issue by this [WeakTimer](https://gist.github.com/Visput/d40c5ceaefbc50c7377597ba0865c9df).

I've already pushed, thanks for your finding!
