### ISSUE TITLE
How can I change event height like Google Calendar

### ISSUE THREAD

**Issue by GreatPotter** [zjfjack/JZCalendarWeekView#18]
Thanks for great work!!!

**Comment by zjfjack** [comment]
The height of the event depends on the duration of this event.
What do you mean for google calendar?

**Comment by GreatPotter** [comment]
Thanks for your reply.
With google calendar, we can adjust each events' height.
But with current library, I could only create new event with fixed height by longpress.

**Comment by zjfjack** [comment]
Okay, I understand what you mean. For that effects, I haven't implemented yet in this library, because this one is too deep to create in a library. 

The effects I made for add new and move are utilised by Apple in around 2016, but for now they changed a lot. You know Google and Apple, they are always updating their system apps, such as Calendar. As a result, I won't add this event height change feature to this library in the near future.

I am so sorry to tell you this and you have to achieve it by yourself.

Thanks

**Comment by GreatPotter** [comment]
I've understood clearly.
Thank you.
