### ISSUE TITLE
How

### ISSUE THREAD

**Issue by xxcombat** [zjfjack/JZCalendarWeekView#25]
Thanks for great work!
I setup calendar with parameter numOfDays = 1.
calendarWeekView.setupCalendar(numOfDays: 1,
                                       setDate: Date(),
                                       allEvents: viewModel.eventsByDate,
                                       scrollType: .pageScroll)

 How can I get the current (selected) date?
**func initDateDidChange(_ weekView: JZBaseWeekView, initDate: Date)** ?
 **initDate** + **numOfDays**  does not contain the current date.

**Comment by zjfjack** [comment]
Hi, xxcombat.

The way initDate + numOfDays should be the current date, you can use
`Calendar.current.date(byAdding: .day, value: 1, to: initDate)` to get the current date.

If you want, I can add one variable to use this way to get the current date.

Thanks

**Comment by xxcombat** [comment]
Thanks for your reply!
I would thank you for adding this variable. 
Thanks

**Comment by zjfjack** [comment]
After trying to add this variable, I realise this `currentDate` is not good for this.
Because in this project, we do have some other week views with different `numOfDays`, which means that the current date is not the date but the first date in that page.

I redo another method called `getDateForSection()` in JZBaseWeekView class, you can use this method by calling `getDateForSection(numOfDays)` to get the first date in the current page, which is your current date in Day View.

I will push it soon. Thanks
